### PR TITLE
Getting started: Add the Cmd+X shortcut to finder

### PR DESCRIPTION
**Pull request by yspreen**
I really love the project! Amazing what hammerspoon can do.

I've been wanting to add this function to finder for a while now, and with hammerspoon it was very easy. Took just a few minutes.

Now since this shortcut sends the keys from its own hook, I added code to disable and re-enable the shortcuts. I think it would make a great addition to the getting started page ✌️

### CODE REVIEW

**Comment by cmsj** [comment]
@yspreen apologies for the slow response. I wonder if this might be even more useful as a Spoon?

**Comment by yspreen** [comment]
As a spoon... Maybe I'm missing something, but what do you mean exactly? @cmsj 

I just thought since it was the reason why I installed this tool in the first place it was a really good showcase for Hammerspoon's functionality!

**Comment by cmsj** [comment]
@yspreen it's possible to distribute self-contained chunks of Hammerspoon functionality as plugin bundles, which we call Spoons: https://github.com/Hammerspoon/hammerspoon/blob/master/SPOONS.md

**Comment by yspreen** [comment]
Yes, I just did a bit of reading, that's an interesting functionality. I'll check it out!

I thought this functionality was worth sharing. And it fit the bill of the other examples to me. But if you think that repo is more appropriate I'll see how I can add it to it 👍

**Pull request closed without merging**
