### PR TITLE
Add docs stylesheet

### PR DESCRIPTION
**Pull request by jasonm23**
Added a stylesheet for the Docs.

screen shot 2015-07-06 at 7 29 55 pm

screen shot 2015-07-06 at 7 29 43 pm

### CODE REVIEW

**Comment by jasonm23** [comment]
Applied to all documentation sets.

**Comment by jasonm23** [comment]
Notes.  

Docs and each child version folder now has a `docs.css`.  Each html file has a `<link>` tag to the relative `docs.css` in it's folder, so that each docs-set remains independent of the others (distribution wise).

I did not update any doc generation scripts, I can get that done for you of course.

**Comment by jasonm23** [comment]
Added a pr to hammerspoon for inclusion of docs.css in the build process.

**Comment by cmsj** [comment]
1675 files! good score :D

Thanks

**Comment by jasonm23** [comment]
Criminally quick to do... 

    find . this-n-that | while read a; do; sed -iBAK 's/head/jam in a stylesheet/'  $a; done; git clean -fd 

... ish

**Pull request merged**
